version: "3"

services:
  angular:
    build: turing-bank-front-end
    ports:
      - "4200:80"
  nest:
    build: turing-bank-back-end
    ports:
      - "3000:3000"
    links:
      - database
    volumes:
      - ./turing-bank-back-end:/app
  database:
    image: mongo
    volumes:
      - ./data-db:/data/db
    