version: '3.7'

services:
  angular:
    build: 
      context: turing-bank-front-end
      target: dev
    restart: always
    ports:
      - "4200:4200"
    # networks:
    #   - testing
  nest:
    build: turing-bank-back-end
    restart: always
    command:  npm run start:prod 
    environment:
      - BASEURL=http://localhost:3000/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - database
    # volumes:
    #   - ./turing-bank-back-end/src:/usr/src/app/src
    # networks:
    #   - testing
  database:
    image: mongo
    restart: always
    # volumes:
    #   - data-db:/data/db
    # networks:
    #   - testing
# volumes:
#     data-db:
# networks:
#        testing: