version: '3.3'

services:
  angular:
    image: djnakudo/frontendturingbankavanade:lts
    restart: always
    ports:
      - "80:80"
  nest:
    image: djnakudo/backendturingbankavanade
    restart: always
    ports:
      - "8080:3000"
    depends_on:
      - database
    volumes:
      - server/src:/usr/src/app/src
  database:
    image: mongo
    restart: always
    volumes:
      - data-db:/data/db
volumes:
    data-db:
    server: