version: '3.3'

services:
  angular:
    build: turing-bank-front-end
    restart: always
    ports:
      - "4200:80"
  nest:
    build: turing-bank-back-end
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - ./turing-bank-back-end/src:/usr/src/app/src
  database:
    image: mongo
    restart: always
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=bruno
      - MONGO_INITDB_ROOT_PASSWORD=marrone
    volumes:
      - ./data-db:/data/db
    