version: '3.3'

services:
  angular:
    image: djnakudo/frontendturingbankavanade:lts
    restart: always
    ports:
      - "80:80"
  nest:
    image: djnakudo/backendturingbankavanade
    restart: always
    environment:
      PORT : 8080
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: mongo
    restart: always
    volumes:
      - data-db:/data/db
volumes:
    data-db:
    server: