version: '3.3'

services:
  angular:
    image: djnakudo/frontendturingbankavanade:lts
    
    restart: always
    ports:
      - "4200:80"
    networks:
      - frontend
    labels:
      - traefik.port=80
      - traefik.frontend.rule=PathPrefix:/
  nest:
    image: djnakudo/backendturingbankavanade
    restart: always
    environment:
      -AZUREMODE=yes
      - BASEURL=http://turingbank.eastus.cloudapp.azure.com/api/v1
    volumes:
      - ./turing-bank-back-end/src:/usr/src/app/src
    environment:
      PORT : 80
    labels:
      - traefik.port=80
      - traefik.frontend.rule=PathPrefix:/api,/docs
    ports:
      - "3000:80"
    depends_on:
      - database
    networks:
      - backend
  database:
    image: mongo
    restart: always
    volumes:
      - data-db:/data/db
    networks:
      - backend
  proxy:
    image: traefik:1.7-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
      - frontend
    ports:
      - "80:80"
    command:
      - --docker
      - --docker.domain=traefik
      - --docker.watch
      - --api
      - --defaultentrypoints=http,https
    labels:
      - traefik.port=8080
      - traefik.frontend.rule=Host:traefik.turingbank.eastus.cloudapp.azure.com
volumes:
    data-db:
networks:
       backend:
       frontend: