version: "3"

services:
  angular:
    build: turing-bank-front-end
    ports:
      - "80:80"
  nest:
    build: turing-bank-back-end
    ports:
      - "3000:3000"
    links:
      - database

  database:
    image: mongo
    